package detectors

import (
	"context"
	"regexp"
	"sync"

	"github.com/go-faker/faker/v4"
)

// EmailPseudonymizer maintains a bidirectional mapping between real and fake
// email addresses. Fake addresses are generated by go-faker and are stable
// within a session (same real address always maps to the same fake address).
type EmailPseudonymizer struct {
	mu         sync.RWMutex
	realToFake map[string]string
	fakeToReal map[string]string
}

func NewEmailPseudonymizer() *EmailPseudonymizer {
	return &EmailPseudonymizer{
		realToFake: make(map[string]string),
		fakeToReal: make(map[string]string),
	}
}

func (p *EmailPseudonymizer) GetOrCreate(real string) string {
	p.mu.RLock()
	if fake, ok := p.realToFake[real]; ok {
		p.mu.RUnlock()
		return fake
	}
	p.mu.RUnlock()

	p.mu.Lock()
	defer p.mu.Unlock()
	if fake, ok := p.realToFake[real]; ok {
		return fake
	}

	fake := faker.Email()
	// Ensure uniqueness: if the generated fake collides, keep regenerating.
	for _, exists := p.fakeToReal[fake]; exists; _, exists = p.fakeToReal[fake] {
		fake = faker.Email()
	}

	p.realToFake[real] = fake
	p.fakeToReal[fake] = real
	return fake
}

func (p *EmailPseudonymizer) Restore(fake string) (string, bool) {
	p.mu.RLock()
	defer p.mu.RUnlock()
	real, ok := p.fakeToReal[fake]
	return real, ok
}

// EmailDetector detects email addresses and replaces them with stable fake
// addresses generated by go-faker, preserving the ability to unredact.
type EmailDetector struct {
	re            *regexp.Regexp
	pseudonymizer *EmailPseudonymizer
}

func NewEmailDetector() *EmailDetector {
	return &EmailDetector{
		// RFC 5321-ish pattern; intentionally broad to avoid false negatives.
		re: regexp.MustCompile(
			`\b[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}\b`,
		),
		pseudonymizer: NewEmailPseudonymizer(),
	}
}

func (d *EmailDetector) Type() string { return "email" }

// Redact replaces each detected email with a stable fake address and invokes
// callback for logging/stats.
func (d *EmailDetector) Redact(ctx context.Context, content string, callback RedactionCallback) string {
	return d.re.ReplaceAllStringFunc(content, func(match string) string {
		fake := d.pseudonymizer.GetOrCreate(match)
		callback(match, "email-address", "Email Address")
		return fake
	})
}

// Unredact replaces fake email addresses in content with the original real
// addresses. Only addresses that were substituted in the current session are
// restored.
func (d *EmailDetector) Unredact(content string) string {
	return d.re.ReplaceAllStringFunc(content, func(match string) string {
		if real, ok := d.pseudonymizer.Restore(match); ok {
			return real
		}
		return match
	})
}
